name: Build job_wizard and package into a Docker container

on:
  workflow_dispatch:
   inputs:
      architecture:
        description: 'Which architecture?'
        required: true
        type: choice
        options:
        - AMD64
        - ARM64
jobs:
  build-and-push:
    name: Build and push job_wizard container to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository code
        uses: actions/checkout@v4
        with:
          repository: segoldin/JobWizard
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: main
          path: JobWizard

      - name: Set up variables
        id: setup
        run: |
          cd JobWizard
          COMMIT_SHA=${{ github.run_id }}-${{ github.run_number }}
          BASE_APPLICATION_NAME="job_wizard"
          REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="docker.io/segoldin68/jobwizard/${BASE_APPLICATION_NAME}"
          echo "REPOSITORY=segoldin68/cmkl_repo" >> $GITHUB_OUTPUT          
          echo "BASE_APPLICATION_NAME=$BASE_APPLICATION_NAME" >> $GITHUB_OUTPUT
          echo "APPLICATION_SUBDIR=$APPLICATION_SUBDIR" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME_LATEST=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME_SHA=${IMAGE_NAME}:${COMMIT_SHA}" >> $GITHUB_OUTPUT
          echo "ENV=production" >> $GITHUB_OUTPUT          
          echo "Will tag image as: $IMAGE_NAME:$COMMIT_SHA and $IMAGE_NAME:latest"          

      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: segoldin68
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.setup.outputs.REPOSITORY }}
          file: ${{ steps.setup.outputs.REPOSITORY }}/docker/Dockerfile
          push: true
          build-args: |
            ENV=${{ steps.setup.outputs.ENV }}
          tags: | 
            ${{ steps.setup.outputs.IMAGE_NAME_LATEST }}
            ${{ steps.setup.outputs.IMAGE_NAME_SHA }}
 
