name: Build job_wizard and package into a Docker container

on:
  workflow_dispatch:
   inputs:
      architecture:
        description: 'Which architecture?'
        required: true
        type: choice
        options:
        - AMD64
        - ARM64
jobs:
  build-and-push:
    name: Build and push job_wizard container to DockerHub
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up variables
        id: setup
        run: |
          BASE_APPLICATION_NAME="job_wizard"
          IMAGE_NAME="${{ secrets.DOCKER_USER }}/${BASE_APPLICATION_NAME}"
          echo "DOCKER_REPO=${{ secrets.DOCKER_USER }}/cmkl_repo" >> $GITHUB_OUTPUT                    
          echo "BASE_APPLICATION_NAME=$BASE_APPLICATION_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME_LATEST=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          echo "ENV=production" >> $GITHUB_OUTPUT          
          echo "Will tag image as: $IMAGE_NAME:latest"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          logout: false

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:      
          file: docker/Dockerfile
          push: true
          build-args: |
            DEBUG=true
          tags: | 
            ${{ steps.setup.outputs.IMAGE_NAME_LATEST }}
            
 
