name: Build job_wizard and package into a Docker container

on:
  workflow_dispatch:
   inputs:
      architecture:
        description: 'Which architecture?'
        required: true
        type: choice
        options:
        - AMD64
        - ARM64
jobs:
  build-and-push:
    name: Build and push job_wizard container to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        env:
          MY_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: echo "My Git PAT is $MY_TOKEN"

      - name: Checkout target repository code
        uses: actions/checkout@v3
        with:
          repository: segoldin/JobWizard
          token: $MY_TOKEN
          ref: main
          path: JobWizard

      - name: Set up variables
        id: vars
        run: |
          cd ${{ steps.setup.outputs.REPOSITORY }}
          COMMIT_SHA=${{ github.run_id }}-${{ github.run_number }}
          BASE_APPLICATION_NAME="job_wizard"
          REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPOSITORY_OWNER}/JobWizard/${{ github.event.inputs.environment }}/${BASE_APPLICATION_NAME}"
          echo "Will tag image as: $IMAGE_NAME:$COMMIT_SHA and $IMAGE_NAME:latest"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.setup.outputs.REPOSITORY }}
          file: ${{ steps.setup.outputs.REPOSITORY }}/docker/Dockerfile
          push: true
          build-args: |
            ENV=${{ steps.setup.outputs.ENV }}
          tags: |
            ${{ steps.vars.outputs.IMAGE_NAME_LATEST }}
            ${{ steps.vars.outputs.IMAGE_NAME_SHA }}

 
